
title: Gabriel Francato # your name (or website title) her
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p>
  Objetivos:
  Meu principal objetivo como engenheiro 'e aplicar de maneira eficiente o conhecimento tencologico
  em setores que ainda considero aquem nesse quesito. (Como o setor financeiro por exemplo)
  </p>
  <p>
  Descricao: 
  Com formacao em engenharia da computacao e experiencias na area de financas e investimento, 
  busco aliar essas duas paixoes. Alem disso, tenho conhecimento de cloud e visao.
  Busco sempre aprender com novas experiencias e pessoas. Acredito que a comunicacao e 
  trabalho em equipe sao trivias no mundo de hoje. 
  </p>
  <a href="https://www.linkedin.com/in/gabriel-francato-87786a18a">View My LinkedIn Profile</a> 
 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
