
title: Gabriel Francato # your name (or website title) her
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Objetivos:
  <br><br>
  Meu principal objetivo como engenheiro 'e aplicar de maneira eficiente o conhecimento tencologico
  em setores que ainda considero aquem nesse quesito. (Como o setor financeiro por exemplo)
  <br><br>
  Descricao: 
  Com formacao em engenharia da computacao e experiencias na area de financas e investimento, 
  busco principalmente aliar essas duas paixoes. Alem disso, tenho conhecimento de cloud e visao, 
  areas que estao revolucioonando diversos setores. Busco sempre aprender com novas experiencias 
  e pessoas, pois acredito que todos tem algo para ensinar, dessa maneira tento me aprimorar nao 
  so profissionamente mas tambem como pessoa. Acredito que a comunicacao e trabalho em equipe sao 
  os principais aspectos para o sucesso.
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
